Repository dobapmin/dobapmin-backend, pull requests merged in 2024-11, with the labels that each got.

#6 pr feat/#5-board-and-gameBoard-model
  app.js
  models/Board.js
  models/GameBoard.js
  routes/board.js
  routes/gameBoard.js
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#10 pr feat/#7-board-list-api
  app.js
  routes/board.js
  routes/main.js
Labels: :sparkles: Feature

#14 pr feat/#8-board-post-api
  .gitignore
  models/Board.js
  models/GameBoard.js
  node_modules/.bin/mime
  node_modules/.bin/nodemon
  node_modules/.bin/nodetouch
  node_modules/.bin/semver
  package-lock.json
  routes/board.js
  routes/gameBoard.js
Labels: :sparkles: Feature

#20 pr feat/#19-fix-game-cancel-api
  routes/gameBoard.js
Labels: :twisted_rightwards_arrows: PullRequest

#24 pr feat/#23-fix-draw-api
  routes/gameBoard.js
Labels: :twisted_rightwards_arrows: PullRequest

#25 Feat/#21 applying scheduling
  app.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  utils/scheduler.js
Labels: :sparkles: Feature

#26 Feat(#22): 뽑기 시작 권한 수정 - 작성자만 가능
  routes/gameBoard.js
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest

#28 pr setting/#27-add-testdb
  db.js
Labels: :twisted_rightwards_arrows: PullRequest, :wrench: Setting

#30 Fix(#29): 익명 상태 수정
  utils/scheduler.js
Labels: :bug: Fix
